---
# Multi-OS Ansible Inventory
# Usage: ansible-playbook -i inventory/hosts.yml set-up-environment.yml

all:
  children:
    # Linux-based systems (SSH connection)
    linux:
      children:
        debian:
          hosts:
            ubuntu-desktop:
              ansible_host: 192.168.1.100
              ansible_user: developer
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
            ubuntu-server:
              ansible_host: 192.168.1.101
              ansible_user: developer
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
              headless: true
        
        archlinux:
          hosts:
            arch-desktop:
              ansible_host: 192.168.1.102
              ansible_user: developer
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
            endeavouros:
              ansible_host: 192.168.1.103
              ansible_user: developer
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
              low_resource: true
    
    # macOS systems (SSH connection)
    darwin:
      hosts:
        macos-intel:
          ansible_host: 192.168.1.104
          ansible_user: developer
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        macos-silicon:
          ansible_host: 192.168.1.105
          ansible_user: developer
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    
    # Windows systems (WinRM connection from Hetzner server)
    windows:
      hosts:
        windows-desktop:
          ansible_host: 192.168.1.106
          ansible_user: developer
          ansible_password: "{{ windows_password }}"
          ansible_connection: winrm
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          ansible_winrm_port: 5985
        windows-laptop:
          ansible_host: 192.168.1.107
          ansible_user: developer
          ansible_password: "{{ windows_password }}"
          ansible_connection: winrm
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          ansible_winrm_port: 5985

  vars:
    # Global variables for all systems
    developer_name: "Your Name"
    developer_email: "your.email@example.com"
    
    # Windows-specific (store in vault)
    windows_password: "{{ vault_windows_password }}"