- name: Docker - Uninstall maybe existing Docker environment
  become: true
  apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent
    purge: yes
  tags:
    - install
    - tools
    - docker

- name: Docker - Update APT Packages
  become: true
  apt:
    force_apt_get: true
    update_cache: true
    state: present
  tags:
    - install
    - tools
    - docker

- name: Docker - Create Directory for Docker GPG Key
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags:
    - install
    - tools
    - docker

- name: Docker - Download Docker GPG Key
  become: true
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  tags:
    - install
    - tools
    - docker

- name: Docker - Add Docker Repository to APT Resources
  become: true
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  tags:
    - install
    - tools
    - docker

- name: Docker - Update APT Packages
  become: true
  apt:
    force_apt_get: true
    update_cache: true
    state: present
  tags:
    - install
    - tools
    - docker

- name: Docker - Install Docker Packages
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  tags:
    - install
    - tools
    - docker

- name: Docker - Install Docker Module for Python
  become: true
  pip:
    name: docker
  tags:
    - install
    - tools
    - docker

- name: Docker - Update APT Packages
  become: true
  apt:
    force_apt_get: true
    update_cache: true
    state: present
  tags:
    - install
    - tools
    - docker

- name: Docker - Create Docker Group
  become: true
  group:
    name: docker
    state: present
  tags:
    - install
    - tools
    - docker

- name: Docker - Add User to Docker Group
  become: true
  user:
    name: "{{ username }}"
    groups: docker
    append: yes
  tags:
    - install
    - tools
    - docker

- name: Docker - Ensure User is added to Docker Group
  command: id -nG "{{ username }}"
  register: user_groups
  tags:
    - install
    - tools
    - docker

