- name: Git - Link Global Git Configuration File
  become: true
  become_user: "{{ username }}"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  with_items:
    - { src: "{{ ansible_env.HOME }}/dotfiles/git/account-config/global", dest: "{{ ansible_env.HOME }}/.gitconfig" }
    - { src: "{{ ansible_env.HOME }}/dotfiles/git/account-config/personal/github", dest: "{{ personal_gh_directory }}/.gitconfig" }
    - { src: "{{ ansible_env.HOME }}/dotfiles/git/account-config/personal/gitlab", dest: "{{ personal_gl_directory }}/.gitconfig" }
    - { src: "{{ ansible_env.HOME }}/dotfiles/git/account-config/personal/gitlab", dest: "{{ work_fitcrew_directory }}/.gitconfig" }
    - { src: "{{ ansible_env.HOME }}/dotfiles/git/account-config/work/github", dest: "{{ ansible_env.HOME }}/work/vds/github/.gitconfig" }
  tags:
    - install
    - core
    - git

