- name: Node.js - Download
  become: true
  command: sh -c "curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash"
  tags:
    - install
    - node.js

- name: Node.js - Install
  become: true
  command: apt-get install -y nodejs
  tags:
    - install
    - node.js


- name: NVM - Install
  #become: true
  become_user: "{{ username }}"
  command: sh -c "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash"
  tags:
    - install
    - node.js

- name: Yarn - Install globally
  become: true
  npm:
    name: yarn
    global: yes
  tags:
    - install
    - node.js

