- name: Git - Clone repositories
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items:
    - { repo: "https://github.com/MannyFay/dotfiles.git", dest: "{{ lookup('env', 'HOME') }}/dotfiles" }
    - { repo: "https://github.com/MannyFay/mannydark.nvim.git", dest: "{{ personal_gh_directory }}/mannydark.nvim" }
    - { repo: "https://github.com/MannyFay/set-up-web-dev-macos.git", dest: "{{ personal_gh_directory }}/set-up-web-dev-macos" }
    - { repo: "https://github.com/MannyFay/short-cuts-and-commands.git", dest: "{{ personal_gh_directory }}/short-cuts-and-commands" }
    - { repo: "https://github.com/MannyFay/start-to-code.git", dest: "{{ personal_gh_directory }}/start-to-code" }
  tags:
    - install
    - projects

- name: Git - Set ownership of repositories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: true
  become: true
  with_items:
    - "{{ lookup('env', 'HOME') }}/dotfiles"
    - "{{ personal_gh_directory }}/mannydark.nvim"
    - "{{ personal_gh_directory }}/set-up-web-dev-macos"
    - "{{ personal_gh_directory }}/short-cuts-and-commands"
    - "{{ personal_gh_directory }}/start-to-code"
  tags:
    - install
    - projects
 
