- name: SSH - Ensure directory exists
  file:
    dest: "{{ localhost_ssh_key_destination | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh


- name: SSH - Copy private key
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "{{ ssh_key_source }}", dest: "{{ localhost_ssh_key_destination }}", mode: 0600 }
    - { src: "{{ ssh_key_source }}.pub", dest: "{{ localhost_ssh_key_destination }}.pub", mode: 0644 }
  tags:
    - dotfiles
    - install
    - ssh
