- name: Python - Install
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - python3
    - python3-pip
    - python3-venv
    - python3-setuptools
  tags:
    - install
    - languages
    - python
