- name: Rust - Check if Rust is already installed
  become: true
  become_user: "{{ username }}"
  command: rustc --version
  register: rust_check
  failed_when: false
  changed_when: false
  tags:
    - install
    - languages
    - rust

- name: Rust - Download and install Rustup
  become: true
  become_user: "{{ username }}"
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustc"
  environment:
    HOME: "{{ ansible_env.HOME }}"
  when: rust_check.rc != 0
  tags:
    - install
    - languages
    - rust

- name: Rust - Add Cargo to PATH in .bashrc
  become: true
  become_user: "{{ username }}"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH="$HOME/.cargo/bin:$PATH"'
    insertafter: EOF
    create: yes
  when: rust_check.rc != 0
  tags:
    - install
    - languages
    - rust

- name: Rust - Add Cargo to PATH in .zshrc
  become: true
  become_user: "{{ username }}"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'export PATH="$HOME/.cargo/bin:$PATH"'
    insertafter: EOF
    create: yes
  when: rust_check.rc != 0
  tags:
    - install
    - languages
    - rust